-- USUARIO
CREATE TABLE IF NOT EXISTS usuario (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(120) NOT NULL
);

-- CURSO
CREATE TABLE IF NOT EXISTS curso (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(120) NOT NULL
);

-- TOPICO
CREATE TABLE IF NOT EXISTS topico (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  titulo VARCHAR(200) NOT NULL,
  mensaje LONGTEXT NOT NULL,
  fecha_creacion DATETIME NOT NULL,
  status VARCHAR(20) NOT NULL,
  autor_id BIGINT NOT NULL,
  curso_id BIGINT NOT NULL,
  CONSTRAINT fk_topico_autor  FOREIGN KEY (autor_id) REFERENCES usuario(id),
  CONSTRAINT fk_topico_curso  FOREIGN KEY (curso_id) REFERENCES curso(id)
);

-- (Opcional) RESPUESTA
CREATE TABLE IF NOT EXISTS respuesta (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  mensaje LONGTEXT NOT NULL,
  topico_id BIGINT NOT NULL,
  fecha_creacion DATETIME NOT NULL,
  autor_id BIGINT NOT NULL,
  solucion BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT fk_respuesta_topico FOREIGN KEY (topico_id) REFERENCES topico(id),
  CONSTRAINT fk_respuesta_autor  FOREIGN KEY (autor_id) REFERENCES usuario(id)
);